global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: flink
    metrics_path: /metrics
    static_configs:
      - targets:
          - flink-jobmanager:9249
          - flink-taskmanager:9249

  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]
